// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5XZ6qKN9dsrAzv_KgFPV6E8yuH7SE3vo',
    appId: '1:1003688998573:web:6d866011c1ecf38eaf7824',
    messagingSenderId: '1003688998573',
    projectId: 'app-note-firebase-v2',
    authDomain: 'app-note-firebase-v2.firebaseapp.com',
    storageBucket: 'app-note-firebase-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOJ3t9AXeilfAfliuhAq_E7io9bGeUl2k',
    appId: '1:1003688998573:android:6c5ba2ed77eec4f6af7824',
    messagingSenderId: '1003688998573',
    projectId: 'app-note-firebase-v2',
    storageBucket: 'app-note-firebase-v2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5XZ6qKN9dsrAzv_KgFPV6E8yuH7SE3vo',
    appId: '1:1003688998573:web:68e6034203ae0b31af7824',
    messagingSenderId: '1003688998573',
    projectId: 'app-note-firebase-v2',
    authDomain: 'app-note-firebase-v2.firebaseapp.com',
    storageBucket: 'app-note-firebase-v2.firebasestorage.app',
  );
}
